DefensieTrainer.WebApp/Controllers/ClusterController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using DefensieTrainer.Domain.IServices;
using DefensieTrainer.WebApp.Models;
using DefensieTrainer.Domain.DTO;
using DefensieTrainer.WebApp.Constants;
using Microsoft.AspNetCore.Authorization;

namespace DefensieTraining.Controllers
{
    [Authorize(Roles = "Manager")]
    public class ClusterController : Controller
    {
        private readonly IClusterService _clusterService;
        private readonly IRequirementServices _requirementService;
        private readonly IPersonService _personService;

        public ClusterController(IClusterService clusterService, IRequirementServices requirementService, IPersonService personService)
        {
            _clusterService = clusterService;
            _requirementService = requirementService;
            _personService = personService;
        }

        [Authorize(Roles = "Manager")]
        public IActionResult CreateRequirement(RequirementViewModel model)
        {
            model.SortTrainingOptions = TrainingTypes.SortTraining.Select(tt => new SelectListItem
            {
                Value = tt.Key.ToString(),
                Text = tt.Value
            }).ToList();

            if (ModelState.IsValid)
            {
                _requirementService.CreateRequirement(model.ToDto());
                return RedirectToAction("Index", "Home");
            }
            return View(model);
        }

        [Authorize(Roles = "Manager")]
        public IActionResult CreateCluster(ClusterViewModel model, string viewRequirements)
        {
            if (!string.IsNullOrEmpty(viewRequirements))
            {
                int selectedRequirementId = int.Parse(viewRequirements);
            }

            if (ModelState.IsValid)
            {
                _clusterService.CreateCluster(model.ToDto());
                ViewBag.CreatedCluster = true;
                return RedirectToAction("ClusterManager");
            }
            else
            {
                return View(model);
            }
        }

        [Authorize(Roles = "Manager")]
        public IActionResult ClusterManager()
        {

            var viewModel = new ClusterViewModel();
            viewModel.Requirements = _requirementService.GetAllRequirements();
            viewModel.Clusters = _clusterService.GetAllClusters();
            return View(viewModel);
        }

        [Authorize(Roles = "Manager")]
        public IActionResult SaveClusters(ClusterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var clustersEntry = ModelState["Clusters"];

                if (clustersEntry != null && clustersEntry.RawValue is List<CreateClusterDto> clusters)
                {
                    foreach (var cluster in clusters)
                    {
                        _clusterService.ChangeCluster(cluster);
                    }
                }
            }
            else
            {
                return View();
            }
            return RedirectToAction("ClusterManager");
        }

        [HttpGet]
        [Authorize(Roles = "Manager")]
        public IActionResult RoleAssignment()
        {
            var model = new RoleAssignmentViewModel
            {
                Roles = RoleTypes.roles.ToDictionary(role => role.Key.ToString(), role => role.Value)
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AssignRole(RoleAssignmentViewModel model)
        {
            if (ModelState.IsValid)
            {
                _personService.UpdateUserRole(model.Email, model.GetRoleName());
            }
            return View("Succes");
        }
    }
}

DefensieTrainer.WebApp/Controllers/LoginController.cs
using DefensieTrainer.Domain.DTO;
using DefensieTrainer.Domain.IServices;
using DefensieTrainer.WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;

namespace DefensieTrainer.Controllers
{
    public class LoginController : Controller
    {
        private readonly IPersonService _userService;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public LoginController(IPersonService userService, IHttpContextAccessor httpContextAccessor)
        {
            _userService = userService;
            _httpContextAccessor = httpContextAccessor;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View("~/Views/Login/Login.cshtml");
        }
        [HttpGet]
        public IActionResult Logout() 
        {
            return View("~/Views/Login/Logout.cshtml");
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                ReadPersonDto user = _userService.AuthenticateUser(model.Email, model.Password);
                if (user != null)
                {
                    var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name, user.Name),
                        new Claim(ClaimTypes.Email, user.Email),
                        new Claim(ClaimTypes.Role, user.Role.ToString())
                    };
                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var authProperties = new AuthenticationProperties
                    {
                        IsPersistent = model.RememberMe
                    };
                    _httpContextAccessor.HttpContext.Session.SetInt32("UserId", user.Id);
                    _httpContextAccessor.HttpContext.Session.SetInt32("ClusterId", user.ClusterId);
                    _httpContextAccessor.HttpContext.Session.SetString("Email", user.Email);

                    await HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(claimsIdentity),
                        authProperties);
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("", "Invalid login attempt.");
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Logout(LoginViewModel loginViewModel)
        {
            HttpContext.Session.Clear();
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }
    }
}

DefensieTrainer.WebApp/Controllers/QuestionController.cs
using DefensieTrainer.Domain.DTO;
using DefensieTrainer.Domain.IServices;
using DefensieTrainer.WebApp.Constants;
using DefensieTrainer.WebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DefensieTrainer.WebApp.Controllers
{
    [Authorize(Roles = "Coach")]
    public class QuestionController : Controller
    {
        private readonly ITrainingService _trainingService;

        public QuestionController(ITrainingService trainingService)
        {
            _trainingService = trainingService;
        }

        [HttpGet]
        public IActionResult ReceiveNextQuestion()
        {
            var training = _trainingService.GetOldestTraining();
            if (training == null)
            {
                return RedirectToAction("NoQuestionsAvailable");
            }

            int trainingSortKey = training.SortTraining;
            string sortTrainingValue;
            if (!TrainingTypes.SortTraining.TryGetValue(trainingSortKey, out sortTrainingValue))
            {
                sortTrainingValue = "Default Value or Handle Null";
            }
            var model = new TrainingFeedbackViewModel
            {
                TrainingId = training.Id,
                Name = training.Name,
                Description = training.Description,
                Amount = training.Amount,
                Meters = training.Meters,
                SortTraining = sortTrainingValue,
                TimeInSeconds = training.TimeInSeconds,
                PersonId = training.PersonId,
            };
            return View(model);
        }


        [HttpGet]
        public IActionResult NoQuestionsAvailable()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Feedback(TrainingFeedbackViewModel model)
        {
            if (model.Feedback is not null)
            {
                CreateFeedbackDto dto = new()
                {
                    TrainingId = model.TrainingId,
                    PersonId = model.PersonId,
                    Feedback = model.Feedback,
                };
                _trainingService.SaveFeedBack(dto);
            }
            return RedirectToAction("ReceiveNextQuestion");
        }
    }
}

DefensieTrainer.WebApp/Controllers/RegisterController.cs
using DefensieTrainer.Domain.DTO;
using DefensieTrainer.Domain.IServices;
using DefensieTrainer.WebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DefensieTrainer.WebApp.Controllers
{
    public class RegisterController : Controller
    {
        private readonly IPersonService _userService;
        private readonly IClusterService _clusterService;
        public RegisterController(IPersonService userService, IClusterService clusterService)
        {
            _userService = userService;
            _clusterService = clusterService;
        }

        [HttpGet]
        public IActionResult Register()
        {
            List<ClusterDto> allClusters = _clusterService.GetAllClusters();
            var Model = new RegisterViewModel();
            foreach (ClusterDto cluster in allClusters)
            {
                Model.AppendCLusterLevel(cluster.ClusterLevel);
            }
            return View("~/Views/Account/Register.cshtml", Model);
        }

        [HttpPost]
        public IActionResult CreateUser(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                _userService.CreateUser(model.ToPostDto());
                return RedirectToAction("Login", "Login");
            }
            else
            {
                return View("~/Views/Account/Register.cshtml", model);
            }
        }
    }
}

DefensieTrainer.WebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using System.Security.Claims
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DefensieTraining</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body class="bodyfixed">
    <div>
        <header>
            <nav class="navbar navbar-expand-sm white navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color: white;">Defensie training</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            @if (User.IsInRole("Manager"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Cluster" asp-action="CreateRequirement">Create Requirement</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Cluster" asp-action="ClusterManager">Cluster Manager</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Cluster" asp-action="RoleAssignment">Role Assignment</a>
                                </li>
                            }
                            @if (User.IsInRole("Coach"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Question" asp-action="ReceiveNextQuestion">Questions</a>
                                </li>
                            }
                            @if (User.IsInRole("User"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Dashboard">User dashboard</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="NewTraining">New training</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="LatestTraining">Your new training</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Feedback">Feedback</a>
                                </li>
                            }
                        </ul>
                        <ul class="navbar-nav">
                            @if (User.Identity.IsAuthenticated)
                            {
                                var userName = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Name)?.Value;
                                var userEmail = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;
                                var userRole = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Role)?.Value;

                                if (!string.IsNullOrEmpty(userName) && !string.IsNullOrEmpty(userEmail))
                                {
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            @userEmail
                                        </a>
                                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                            <li>@userRole</li>
                                            <li><a class="dropdown-item" href="#">Profile</a></li>
                                            <li>
                                                <form asp-controller="Login" asp-action="Logout" method="post">
                                                    <button type="submit">Logout</button>
                                                </form>
                                            </li>
                                        </ul>
                                    </li>
                                }
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Login">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Register" asp-action="Register">Register</a>
                                </li>
                            }
                        </ul>

                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DefensieTraining - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @RenderSection("Scripts", required: false)
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>